### ISSUE TITLE
Incorrect and maybe dangerous result

### ISSUE THREAD

**Issue by entertainyou** [Tjatse/node-readability#15]
```
describe('decode',function(){
  it('TEST',function(done){
    var article = '<title>title</title>' +
        '<body>' +
        '<p foo="&quot; width=1000 onclick=alert(10) test"> HELLO WORLD</p>' +
        '</body>';

    read({
      html: article,
    }, function(err, art){
      should.not.exist(err);
      console.log('art', art.content);
      done();
    });
  });
});
```

The output is 
```
art <p foo="" width=1000 onclick=alert(10) test"> HELLO WORLD</p>
```
makes the html content not safe to use.

The issue seems lies in returning a decoded version of html, why decode it(Also, the decodeEntities option parsed to cheerio is set to false, maybe can set it to true)?

**Comment by miduga** [comment]
Have you tried to put `tidyAttrs` property to true? Anyway I think that you're right as it's not a desirable output.

**Comment by Tjatse** [comment]
It's some historical issues of `cheerio`, Cause' `cheerio` can not decode Chinese correctly sometimes, e.g. `title` attribute will be `&#1234;&#5678;` with some node vers. so try to use `tidyAttrs` as @miduga recomended.

**Comment by entertainyou** [comment]
@Tjatse , use tidyAttrs can work sometimes, but for the my case, the html content is more like(> is encoded in one of p's attribute value)
```
var read = require('../'),
    chai = require('chai'),
    expect = chai.expect,
    should = chai.should();

describe('decode',function(){
  it('TEST1',function(done){
    var article = '<title>title</title>' +
        '<body>' +
        '<p foo="abc&gt;def"> HELLO WORLD</p>' +
        '</body>';

    read({
      html: article,
      tidyAttrs: true,
    }, function(err, art){
      should.not.exist(err);
      console.log('art', art.content);
      done();
    });
  });
});
```

when ```tidyAttrs``` is false, the result is ```<p foo="abc>def"> HELLO WORLD</p>```
when ```tidyAttrs``` is true, the result is ```<p>def"> HELLO WORLD</p>```.

**Comment by entertainyou** [comment]
@Tjatse ,do you have a small case of cheerio fails to decode chinese?

**Comment by Tjatse** [comment]
cheeriojs/cheerio#565

**Comment by Tjatse** [comment]
I can simply fixed this by removing the `entities` module and let `cheerio` handle the encodings by itself, but unfortunately, this problem occasionally happening in `v0.19.0` and I need time to dig deep.

**Comment by Tjatse** [comment]
I think we must get this fixed somehow immediately, a new option like `forceDecode`?
- `forceDecode: false` decodes by `cheerio`.
- `forceDecode: true` fallback to decode context by `entities` but not `cheerio`.

**Comment by entertainyou** [comment]
An option should be great, :+1:

**Comment by Tjatse** [comment]
I've published an alpha ver. `read-art@0.4.6-alpha`. The GA will come soon.

**Comment by entertainyou** [comment]
What does GA mean?

**Comment by Tjatse** [comment]
General Availability -> `0.4.6`
