### ISSUE TITLE
Some titles are broken

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#23]
URL:
http://www.abc.es/economia/abci-presidente-ceoe-reconoce-preocupacion-dificultad-para-formar-gobierno-201601271013_noticia.html

Title expected: El presidente de la CEOE reconoce su «preocupación» por la dificultad para formar gobierno

Title from read-art: El presidente de la CEOE reconoce su

The problem is with the < and > symbols that are being cut by searching a better title. It might be a good idea to only cut titles if those symbols are separating the first or last word (or near  the beggining or the end of the string).

**Comment by Tjatse** [comment]
A new option will be exposed to let user customizing `title` extraction.

**Comment by miduga** [comment]
That would be nice, thanks!

**Comment by Tjatse** [comment]
Try the lastest ver. by:
```javascript
read({
  betterTitle: function(title){
    return title;
  },
  // ...
})
```
or
```javascript
read({
  betterTitle: 1000,
  // ...
})
```
