### ISSUE TITLE
Use JavaScript Standard Style [enhancement]

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#24]
I've been following the project for a while and we're using on an experimental project on my company. Now, while I want to contribute with Pull Requests I find that would be nice to follow some guideline and stick with it. What about following the javascript standard style to code it https://github.com/feross/standard

The most famous editors, like Sublime Text and Atom, have plugins to check on realtime the syntax and tell you what's wrong with your code to stick with the style.

Also, it would be great to consider adding some ES6 syntax (depending on the node version that the project want to support).

**Comment by Tjatse** [comment]
Sounds good :+1:

**Comment by miduga** [comment]
Fantastic! :+1: Just share with me the target node version of the project and if you like to start receiving pull requests for moving the project to standard style. :)

**Comment by Tjatse** [comment]
supported since v0.4.6-alpha ^^

**Comment by miduga** [comment]
Great! :)
