### ISSUE TITLE
Extra score for items with articleBody itemprop (no matter if article or div)

### ISSUE THREAD

**Issue by midudev** [Tjatse/node-readability#25]
Now initNode function in reader.js gives 20 points to article tag. There's an itemprop used on some publications that defines where is the article body directly, no matter the tag where is used.

```
<div itemprop="articleBody" class="article-body-text>
    <p>Article main body text... lorem ipsum...</p>
</div>
```

According to schema.org (https://schema.org/articleBody):

> The actual body of the article.
> Usage: Over 1,000,000 domains

**Comment by miduga** [comment]
An example of publication using it: http://www.lequipe.fr/Tennis/Actualites/Open-d-australie-gael-monfils-s-arrete-en-quart-de-finale/628639

**Comment by Tjatse** [comment]
Pretty nice, thanks.

**Comment by miduga** [comment]
Thanks to you, keep up with the good work!
