### ISSUE TITLE
Remove inline styles

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#3]
Inlined styles are maintained over the result of the content. Might it be better to rip inline styles off.

You can try with that url (it's from Spain): `http://www.abc.es/deportes/futbol/20150923/abci-celta-barcelona-liga-201509232234.html`

    "content": "<p>El <span style=\"font-weight:bold;font-style:normal;\">Celta </span>es un equipo incómodo, ganarle no es fácil y exige un gasto físico muy desagradable. ...",

Example URLs:
http://www.sport.es/es/noticias/real-madrid/higuain-niega-las-criticas-cristiano-ronaldo-4543758
http://www.abc.es/deportes/futbol/20150923/abci-celta-barcelona-liga-201509232234.html

**Comment by miduga** [comment]
Btw, amazing work. :+1: I hope to be able to collaborate as soon as I get some time!

**Comment by Tjatse** [comment]
Appreciate!!

**Comment by miduga** [comment]
I've added another example to the initial comment if that helps.

**Comment by Tjatse** [comment]
Gotcha, and thank you very much, I'll implement this ASAP (It's Mid Autumn Festival and National day this days, I'll back to my laptop on 10/8, sorry :) ).

**Comment by miduga** [comment]
No problem! Enjoy the holidays! ;)

**Comment by Tjatse** [comment]
Sorry for the delay, try to set `tidyAttrs` to `true` [1](https://github.com/Tjatse/node-readability#usage):
```javascript
read('http://www.abc.es/deportes/futbol/20150923/abci-celta-barcelona-liga-201509232234.html', { tidyAttrs: true }, function(err, art, options, resp){
	if (err) {
    console.log('[ERROR]', err.message);
    return;
  }
  if (!art) {
    console.log('[WARNING] article not exist');
    return;
  }

  console.log('[INFO]', 'title:', art.title);
  console.log('[INFO]', 'content:', art.content);
});
```

**Comment by Tjatse** [comment]
feel free to reopen this or file a new one if problem still exists
