### ISSUE TITLE
Improving readability of the code and refactor methods

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#35]
In order to improve readability of the code and also keep files maintanable, I would like to separate functions in smaller methods and separate files in modules (for example, aiming to separate reader.js in smaller stateless modules), one for scoring, for example.

The reason: keep it simple in order to attract people to collaborate and, also, improve the maintainability while keeping the functionality intact. I'll start to send pull requests to it. :)

**Comment by Tjatse** [comment]
Sounds reasonable;)
