### ISSUE TITLE
Detect and use charset if not set

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#4]
Right now, utf8 is by default the charset but it will give problems if the website is using a different charset.  For example this URL: http://www.elimparcial.com/EdicionEnlinea/Notas/Sonora/22092015/1010394-Firma-CPA-convenio-con-Cofemer.html

It would be great if the script detects the charset before parsing it as, you can see, now it's returning wrong encoding to this kind of URLs.

~~Also, and I suppose that related, the option for charset is unused in the code right now.~~

**Comment by Tjatse** [comment]
The `charset` works for me, and `req-fast` [detects the charset automatically](https://github.com/Tjatse/req-fast/blob/master/lib/req.js#L110-L139). I'll test your URL tomorrow and figure it out.

**Comment by miduga** [comment]
Okey, as I can see:

- charset is working as expected. My wrong.
- the webpage is using UTF8 while in his meta charset is using ISO-8859-1.

So, the problem, in fact, is that the charset is working like a charm but the website has the wrong charset in the header. :) Problem solved! Thanks!

**Comment by Tjatse** [comment]
Yes, you gotcha :)
