### ISSUE TITLE
Links are removed if <p> is missing

### ISSUE THREAD

**Issue by miduga** [Tjatse/node-readability#5]
Solved the mystery about the charset I came along with another problem with the same URL.

`http://www.elimparcial.com/EdicionEnlinea/Notas/Sonora/22092015/1010394-Firma-CPA-convenio-con-Cofemer.html`

With the same article, and forcing the charset to use 'utf-8' some links are missing.The reason behind, I guess, is that the article is missing `<p>` for the content and is using instead `<div>` then the links inside are being treated as child nodes and the links doesn't have enough length to be putted.

I tried to add `if ((tagName == 'span' || tagName == 'font' || tagName == 'a' ) && textLen > 0)` but then the paragraph is closed before appending the link.

**Comment by miduga** [comment]
Another example for this behaviour with this link:
http://www.macrumors.com/2015/10/19/mission-motors-ceases-operations-apple/

**Comment by Tjatse** [comment]
thanks, I just wanna handle this in an elegant way :)

**Comment by miduga** [comment]
:+1: Perfect! :)

**Comment by Tjatse** [comment]
This should be fixed via v0.4.4, feel free to reopen this or file a new one if the issue still exists.
